export component AI1 inherits Rectangle {
    callback go_back();
    ai := Rectangle {
        frame-52 := Image {
            x: 12px;
            y: 36px;
            width: 32px;
            height: 32px;
            colorize: white;
            TouchArea {
                width: 50px;
                height: 50px;
                clicked => {
                    root.go_back();
                }
            }
            source: @image-url("assets/arrow-left-wide-line.svg");
        }
        frame-12 := Rectangle {
            x: 47px;
            y: 127.5px;
            width: 145.312px;
            height: 64.875px;
            border-radius: 99px;

            frame-74 := Rectangle {
                x: 50.781px;
                y: 0px;
                width: 43.75px;
                height: 43.75px;
                rectangle-2 := Rectangle {
                    x: 6.25px;
                    y: 6.25px;
                    width: 31.25px;
                    height: 31.25px;
                    border-radius: 1560.938px;
                    border-width: 6.25px;
                    border-color: @linear-gradient(165deg, #cde800 0%, #efdede 50%, #dee36f 100%);
                }
            }
            frame-75 := Rectangle {
                x: 22.156px;
                y: 46.875px;
                width: 101px;
                height: 18px;
                ai_text := Text {
                    x: 0;
                    y: 0;
                    text: "AI";
                    color: #ffffff;
                    font-family: "Roboto Mono";
                    font-size: 12px;
                    font-weight: 500;
                    horizontal-alignment: left; 
                }
                coming-soon := Text {
                    x: 19px;
                    y: 0px;
                    text: "Coming Soon";
                    color: #ffffffcc;
                    font-family: "Roboto Mono";
                    font-size: 12px;
                    font-weight: 500;
                    horizontal-alignment: left; 
                }
            }
        }
        frame-128 := Rectangle {
            x: 12px;
            y: 250px;
            width: 216px;
            height: 58px;
            underconstruction := Text {
                y: 0px;
                text: "--- Underconstruction ---";
                color: #ffffff;
                font-family: "Roboto Mono";
                font-size: 10px;
                font-weight: 500;
                horizontal-alignment: center;
            }
            frame-123 := Rectangle {
                x: 0px;
                y: 27px;
                width: 216px;
                height: 31px;
                button := Rectangle {
                    x: 0px;
                    y: 0px;
                    width: 107px;
                    height: 31px;
                    background: #ffffff1a;
                    ask-ai := Text {
                        x: 35.5px;
                        y: 8px;
                        text: "Ask AI";
                        color: #ffffff;
                        font-family: "Roboto Mono";
                        font-size: 10px;
                        font-weight: 500;
                        horizontal-alignment: left; 
                    }
                }
                button2 := Rectangle {
                    x: 109px;
                    y: 0px;
                    width: 107px;
                    height: 31px;
                    background: #ffffff1a;
                    ask-ai_text := Text {
                        x: 30px;
                        y: 8px;
                        text: "AI Agent";
                        color: #ffffff;
                        font-family: "Roboto Mono";
                        font-size: 10px;
                        font-weight: 500;
                        horizontal-alignment: left; 
                    }
                }
            }
        }
    }
}
        
    
