import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import {HomeLock} from "home-lock.slint";
import {Home} from "home.slint";
import {IoT} from "iot.slint";
import { TopBar } from "top-bar.slint";
import {LoadingScreenText} from "loading-screen.slint";
import {Sensor} from "sensors.slint";
import {AI1} from "ai_screen_1.slint";
import { Game } from "game.slint";
import { DeviceLink } from "device-link.slint";
import { DeviceLinkEd} from "device-linked.slint";
import { DeviceLinkSucess } from "link-device-sucess.slint";
import { WifiMenuBar } from "wifi-component.slint";
import { WiFiConfig } from "wifi-config.slint";

// export {
//     Home,
//     IoT,
//     HomeLock,
//     TopBar,
//     DeviceLink,
//     DeviceLinkEd,
//     DeviceLinkSucess
// }
export enum ScreenState {
    HomeLock,
    Home,
    LoadingSreen,
    IOT,
    Sensor,
    AI,
    Game,
    LinkDevice,
    LinkDeviceSucess,
    LinkDeviceDone,
    Setting,
}
export struct ScreenStatus {

}
export component AppWindow inherits Window {
    preferred-height: 320px;
    preferred-width: 240px;
    background: #000000;
    in-out property <ScreenState> screen_state: HomeLock;
    property <int> current_index: 0;

    TopBar {
        x: 0;
        y: 0;
    }

    HomeLock {
        visible: root.screen_state == ScreenState.HomeLock;
        x: 0;
        y: 0;
        go_to_home_page => {
            root.screen_state = ScreenState.Home;
        }
    }
    Home {
        x: 0;
        y: 0;
        visible: root.screen_state == ScreenState.Home;
    }
    // TopBar {
    //     x: 0;
    //     y: 0;
    // }
    // Home {
    //     x: 0;
    //     y: 0;
    // }
    // IoT {
    //     visible: true;
    //     x: 0;
    //     y: 0;
    // }

    // IoT {
    //     x: 0;
    //     y: 0;
    // }
    // Home {
    //     x: 0;
    //     y: 0;
    // }
    // LoadingScreenText {
    //     x: 0;
    //     y: 0;
    // }
    // Sensor {

    // }
    // AI1{
    //    x: 0;
    //    y: 0;
    // }
    // DeviceLinkSucess{
    //     x: 0;
    //     y: 0;
    // }
    // WifiMenuBar {
    //     x: 0;
    //     y: 0;
    // }
    // WiFiConfig {
    //     x: 0;
    //     y: 0;
    // }
}

export component OldApp inherits Window {
    in property <image> current_frame;
    in property <string> current_time;
    background: #000000;

    Image {
        y: 61px;
        x: 43px;
        source: current_frame;
        width: 160px;
        height: 160px;
    }
    
    HorizontalLayout {
        x: 0;
        y: 0;
        width: 240px;
        height: 28px;
        padding-bottom: 8px;
        padding-right: 12px;
        padding-top: 8px;
        padding-left: 12px;
        spacing: 8px;
        vertical-stretch: 0;
        alignment: LayoutAlignment.space-around;
        horizontal-stretch: 0;
        max-width: 0px;
        min-width: 0px;
        HorizontalLayout {
            width: 88.5px;
            alignment: LayoutAlignment.start;
            height: 12px;
            spacing: 8px;
            padding-left: 0;
            Image {
                source: @image-url("assets/wifi.svg");
            }
            HorizontalLayout {
                spacing: 4px;
                width: 26px;
                height: 12px;
                Image {
                    source: @image-url("assets/mind-map.svg");
                }
                in property <string> signal;
                Text {
                    font-family: "Instrument Sans";
                    font-weight: 500;
                    vertical-alignment: center;
                    text: signal;
                    font-size: 8px;
                    color: #89DD47;
                    letter-spacing: 0px;
                }
                signal: "10";
            }
        }

        HorizontalLayout {
            alignment: LayoutAlignment.end;
            spacing: 4px;
            width: 88px;
            height: 12px;
            in property <string> battery_percent;
            Image {
                source: @image-url("assets/battery-fill.svg");
                vertical-alignment: center;
            }
            Text {
                font-family: "Instrument Sans";
                text: battery_percent;
                font-size: 8px;
                color: #FFFFFF;
                font-weight: 500;
                vertical-alignment: center;
            }
            battery_percent: "95%";
        }
    }

    Text {
        y: 10px;
        x: 108.5px;
        font-family: "Instrument Sans";
        text: current_time;
        font-italic: false;
        font-size: 8px;
        color: white;
        font-weight: 500;
        horizontal-alignment: TextHorizontalAlignment.center;
    }
    
    HorizontalLayout {
        x: 12.3px;
        y: 54.4px;
        width: 214px;
        height: 48px;
        spacing: 14.72px;
        alignment: LayoutAlignment.stretch;
        VerticalLayout {
            alignment: LayoutAlignment.space-around;
            width: 26px;
            height: 27px;
            in property <int> day; // 10, 20, ..
            in property <string> week_day; // MON, TUE, FRI,...
            Text {
                font-family: "Instrument Sans";
                horizontal-alignment: center;
                color: #FFFFFF;
                text: week_day;
                vertical-alignment: TextVerticalAlignment.center;
                font-size: 10px;
                font-weight: 400;
            }
            vertical-stretch: 0;
            week_day: "FRI";
            Text {
                horizontal-alignment: center;
                color: #F9C22B;
                text: day;
                font-size: 20px;
                font-weight: 400;
            }
            day: 20;
        }
        Text {
            width: 174px;
            height: 48px;
            horizontal-alignment: TextHorizontalAlignment.left;
            font-weight: 400;
            text: current_time;
            vertical-alignment: TextVerticalAlignment.center;
            font-size: 56px;
            color: #FFFFFF;
        }
    }


    SwipeGestureHandler {
        height: 105px;
        width: 240px;
        x: 0px;
        y: root.height - self.height;
        HorizontalLayout {
            
            x: 60.8px;
            y: 66.56px;
            width: 119.04px;
            alignment: LayoutAlignment.space-between;
            height: 15.36px;
            spacing: 7.68px;
            Text {
                font-family: "Instrument Sans";
                text: "Swipe up to start";
                font-size: 12px;
                color: #FFFFFF;
            }
            Image {
                horizontal-alignment: ImageHorizontalAlignment.center;
                image-fit: ImageFit.preserve;
                source: @image-url("assets/arrow-up-double-line.svg");
            }
        }
    }
    current_time: "09:42";
    preferred-height: 320px;
    preferred-width: 240px; 
}