import { Button, VerticalBox } from "std-widgets.slint";

export global ImageLoader {
    pure callback load_gif_frame(string, int) -> image;
}
export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    default-font-size: 0px;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
            color: green;
        }
        
        Image {
            image-fit: ImageFit.cover;
            source: ImageLoader.load_gif_frame("asssets/cat_1.gif", animation-tick() / 1ms);
        }

    }
    preferred-height: 320px;
    preferred-width: 240px;
    
}
