export component DeviceLinkEd inherits Window {
    frame-8 := Rectangle {
        x: 0px;
        y: 158.88px;
        width: 240px;
        height: 161px;
        background: #1c1c1c;
        frame-90 := Rectangle {
            x: 8px;
            y: 8px;
            width: 224px;
            height: 24px;
            link-device := Text {
                x: 8px;
                y: 4.5px;
                text: "Link Device";
                color: #ededed;
                font-family: "Roboto Mono";
                font-size: 10px;
                font-weight: 700;
                horizontal-alignment: center;
            }
            frame-96 := Image {
                x: 200px;
                y: 0px;
                width: 24px;
                height: 24px;
                source: @image-url("assets/close-line.svg");
            }
        }
        frame-47 := Rectangle {
            x: 8px;
            y: 38px;
            width: 224px;
            height: 115px;
            frame-91 := Rectangle {
                x: 8px;
                y: 12px;
                width: 208px;
                height: 35px;
                device-id := Text {
                    x: 0px;
                    y: 0px;
                    text: "Device ID";
                    color: #ffffffcc;
                    font-family: "Roboto Mono";
                    font-size: 10px;
                    font-weight: 500;
                    horizontal-alignment: left;
                }
                joam-3m34 := Text {
                    x: 0;
                    y: 17px;
                    text: "JOAM...3M34";
                    color: #ededed;
                    font-family: "Roboto Mono";
                    font-size: 12px;
                    font-weight: 700;
                    horizontal-alignment: center;
                }
            }
            frame-92 := Rectangle {
                x: 8px;
                y: 59px;
                width: 208px;
                height: 32px;
                wallet := Text {
                    x: 0;
                    y: 0;
                    text: "Wallet";
                    color: #ffffffcc;
                    font-family: "Roboto Mono";
                    font-size: 10px;
                    font-weight: 500;
                    horizontal-alignment: left;
                }
                _0x2398-3284 := Text {
                    x: 0;
                    y: 17px;
                    text: "0x2398...3284";
                    color: #89dd47;
                    font-family: "Roboto Mono";
                    font-size: 12px;
                    font-weight: 700;
                    horizontal-alignment: center;
                }
            }
        }
    }
}