export global DeviceQR {
    pure callback get_qr() -> image;
}
export component DeviceLink inherits Rectangle {
    in-out property <image> qr_image;
    in-out property <string> device-id;
    callback go_back;
    frame-8 := Rectangle {
        x: 0px;
        y: 96.52px;
        width: 240px;
        height: 223.48px;
        background: #1c1c1c;
        frame-90 := Rectangle {
            x: 7.68px;
            y: 7.68px;
            width: 224.64px;
            height: 24px;
            link-device := Text {
                x: 8px;
                y: 4.5px;
                text: "Link Device";
                color: #ededed;
                font-family: "Roboto Mono";
                font-size: 10px;
                font-weight: 700;
                horizontal-alignment: center; 
            }
            frame-96 := Rectangle {
                x: 200.64px;
                y: 0px;
                width: 24px;
                height: 24px;
                background: #ffffff1a;
                close-line := Image {
                    x: 4px;
                    y: 4px;
                    width: 16px;
                    height: 16px;
                    colorize: #ffffff;
                    source: @image-url("assets/close-line.svg");
                }
                TouchArea {
                    clicked => {
                        root.go_back();
                    }
                }
            }
        }
        frame-47 := Rectangle {
            x: 7.68px;
            y: 36.8px;
            width: 224.64px;
            height: 179px;
            qr-code := Image {
                y: -10px;
                width: 120px;
                height: 120px;
                source: qr_image;
            }
            frame-91 := Rectangle {
                x: 72.32px;
                y: 120px;
                width: 80px;
                height: 35px;
                device-id := Text {
                    x: 13.5px;
                    y: 1px;
                    text: "Device ID";
                    color: #ffffffcc;
                    font-family: "Roboto Mono";
                    font-size: 10px;
                    font-weight: 500;
                    horizontal-alignment: left; 
                }
                joam-3m34 := Text {
                    x: 0;
                    y: 17px;
                    text: root.device-id;
                    color: #ededed;
                    font-family: "Roboto Mono";
                    font-size: 12px;
                    font-weight: 700;
                    horizontal-alignment: center; 
                }
            }
        }
    }
}