import { Button, VerticalBox, HorizontalBox, ProgressIndicator } from "std-widgets.slint";

import {RoundProgress} from "roundprogress.slint";

export enum GameState {
    Normal, // Display None
    Playing, 
    Eating,
    Sleeping
}

export enum Animal {
    LunaFluff,
    Mechapup,
    Chirplunk
}
export global AnimationSwitch {
    pure callback animation_switch(game_state: GameState, animal: Animal);
}
export component Game inherits Rectangle{

    in-out property <GameState> game_state: GameState.Normal;
    in-out property <Animal> animal: Animal.Chirplunk;
    in-out property <int> animal_index: 1;
    in-out property <bool> timer_run;
    callback go_back();
    callback display_device();
    pure callback set_current_frame() -> image;

    function get_animal() -> string {
        if (root.animal == Animal.Chirplunk) {
            return "Chirplunk";
        }
        if (root.animal == Animal.LunaFluff) {
            return "Lunafluff";
        }
        if (root.animal == Animal.Mechapup) {
            return "Mechapup";
        }
        return "Mechapup";
    }
    function switch_animal(next: bool) -> Animal {
        if (next == true) {
            root.animal_index = root.animal_index + 1;
            if (root.animal_index > 3) {
                root.animal_index = 1;
            }
        }
        else {
            root.animal_index = root.animal_index - 1;
            if root.animal_index < 1 {
                root.animal_index = 3;
            }
        }
        if (root.animal_index == 1) {
            root.animal = Animal.Chirplunk;
        }
        if (root. animal_index == 2) {
            root.animal = Animal.LunaFluff;
        }
        if (root. animal_index == 3) {
            root.animal = Animal.Mechapup;
        }
        AnimationSwitch.animation_switch(root.game_state, root.animal);
        return Animal.Chirplunk;
    }
    frame-7 := Rectangle {
        x: 12px;
        y: 32px;
        width: 216px;
        height: 232px;
        border-color: #ffffff33;
        frame-47 := Rectangle {
            x: 0px;
            y: 0px;
            width: 216px;
            height: 232px;
            Image {
                x: 31.2px;
                y: 0px;
                source: root.set_current_frame();
                width: 160px;
                height: 160px;
            }
            frame-87 := Rectangle {
                x: 58px;
                y: 195px;
                width: 100.769px;
                height: 19px;
                arrow-left-wide-line := Image {
                    x: 0;
                    y: 0;
                    width: 16px;
                    height: 16px;
                    source: @image-url("assets/arrow-right-wide-line.svg");
                    TouchArea {
                        height: 40px;
                        width: 40px;
                        clicked => {
                            switch_animal(false);
                        }
                    }
                }
                frame-86 := Rectangle {
                    x: 26px;
                    y: 0px;
                    width: 54px;
                    height: 19px;
                    chiplunk := Text {
                        text: get_animal();
                        color: #ffffff;
                        font-family: "Roboto Mono";
                        font-size: 10px;
                        font-weight: 500;
                        horizontal-alignment: left; 
                    }
                }
                arrow-right-wide-line:= Image {
                    x: 84.769px;
                    y: 0px;
                    width: 16px;
                    height: 16px;
                    colorize: white;
                    source: @image-url("assets/arrow-right-wide-line_1.svg");
                    TouchArea {
                        height: 40px;
                        width: 40px;
                        clicked => {
                            switch_animal(true);
                        }
                    }
                }
            }
        }
        frame-52 := Rectangle {
            x: 0px;
            y: 0px;
            width: 32px;
            height: 32px;
            TouchArea {
                clicked => {
                    root.go_back();
                }
            }
            Image {
                colorize: white;
                source: @image-url("assets/arrow-left-wide-line.svg");
            }
        }
        button-icon_right := Rectangle {
            x: 184px;
            y: 0px;
            width: 32px;
            height: 32px;
            border-width: 1px;
            border-color: #ffffff33;
            phone-camera-line := Image {
                x: 8px;
                y: 8px;
                width: 16px;
                height: 16px;
                source: @image-url("assets/phone-camera-line.svg");
                TouchArea {
                    width: 40px;
                    height: 40px;
                    clicked => {
                        display_device();
                    }
                }
            }
        }
    }

    food-cake := Image {
        visible: root.game_state == GameState.Eating;
        x: 127.52px;
        y: 160.64px;
        width: 42.24px;
        height: 42.24px;
        source: @image-url("assets/cake.svg");
    }
    action-ball := Image {
        visible: root.game_state == GameState.Playing;
        x: 107.52px;
        y: 160.64px;
        width: 42.24px;
        height: 42.24px;
        source: @image-url("assets/ball.svg");
    }
    action-sleep := Image {
        visible: root.game_state == GameState.Sleeping;
        x: 139.52px;
        y: 104.64px;
        width: 42.24px;
        height: 42.24px;
        source: @image-url("assets/sleep.svg");
    }
    frame-10 := Rectangle {
        x: 0px;
        y: 263.04px;
        width: 240px;
        height: 56.96px;
        progress_timer:= Timer {
            interval: 200ms;
            running: true;
            triggered => {
                if root.timer_run == true {
                    if root.game_state == GameState.Eating {
                        eat.progress_value = eat.progress_value + 10;
                        if (eat.progress_value > 100) {
                            eat.progress_value = 0;
                            root.game_state = GameState.Normal;
                            root.timer_run = false;
                            AnimationSwitch.animation_switch(root.game_state, root.animal);
                        }
                    }
                    if root.game_state == GameState.Playing {
                        play.progress_value = play.progress_value + 10;
                        if (play.progress_value > 100) {
                            play.progress_value = 0;
                            root.game_state = GameState.Normal;
                            root.timer_run = false;
                            AnimationSwitch.animation_switch(root.game_state, root.animal);
                        }
                    }
                    if root.game_state == GameState.Sleeping {
                        sleep.progress_value = sleep.progress_value + 10;
                        if (sleep.progress_value > 100) {
                            sleep.progress_value = 0;
                            root.game_state = GameState.Normal;
                            root.timer_run = false;
                            AnimationSwitch.animation_switch(root.game_state, root.animal);
                        }
                    }
                }
            }
        }
        eat := RoundProgress {
            x: 8px;
            y: 8px;
            width: 69px;
            height: 40px;
            inner_color: #f9c22b;
            TouchArea {
                clicked => {
                    if root.game_state == GameState.Normal {
                        root.game_state = GameState.Eating;
                        root.timer_run = true;
                        AnimationSwitch.animation_switch(root.game_state, root.animal);
                    }
                }
            }
            Image {
                source: @image-url("assets/icon-park-outline_hamburger.svg");
            }
        }
        play := RoundProgress {
            x: 84px;
            y: 8px;
            width: 69px;
            height: 40px;
            inner_color: #89dd47;
            TouchArea {
                clicked => {
                    if root.game_state == GameState.Normal {
                        root.game_state = GameState.Playing;
                        root.timer_run = true;
                        AnimationSwitch.animation_switch(root.game_state, root.animal);
                    }
                }
            }
            Image {
                source: @image-url("assets/icon-park-outline_game-three.svg");
            }
        }
        sleep := RoundProgress {
            x: 160px;
            y: 8px;
            width: 69px;
            height: 40px;
            inner_color: #d39bf7;
            TouchArea {
                clicked => {
                    if root.game_state == GameState.Normal {
                        root.game_state = GameState.Sleeping;
                        root.timer_run = true;
                        AnimationSwitch.animation_switch(root.game_state, root.animal);
                    }
                }
            }
            Image {
                colorize: #ffffff;
                source: @image-url("assets/solar_moon-sleep-linear.svg");
            }
        }
    }
}
