import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { TopBar } from "top-bar.slint";
export component Home inherits Rectangle {
    in property <string> time;
    callback go_to_sensor;
    callback go_to_game;
    callback go_to_ai;
    callback go_to_setting;
    callback go_to_device_link;
    callback device_link;
    callback go_to_iot;

    frame-108 := Rectangle {
        x: 12px;
        y: 36px;
        width: 216px;
        height: 75px;
        frame-61 := Rectangle {
            x: 0px;
            y: 0px;
            width: 216px;
            height: 38px;
            frame-104 := Rectangle {
                x: 0px;
                y: 0px;
                width: 132px;
                height: 38px;
                frame-4 := Rectangle {
                    x: 0px;
                    y: 0px;
                    width: 32px;
                    height: 38px;
                    background: #ffffff1a;
                    in property <string> week_day;
                    in property <int> date;
                    wd := Text {
                        // x: 6px;
                        y: 6px;
                        text: week_day;
                        color: #ffffff;
                        font-family: "Roboto Mono";
                        font-size: 7.5px;
                        font-weight: 400;
                        horizontal-alignment: center; 
                    }
                    week_day: "FRI";
                    date_text := Text {
                        x: 7.5px;
                        y: 18px;
                        text: date;
                        color: #f9c22b;
                        font-family: "Roboto Mono";
                        font-size: 13.5px;
                        font-weight: 500;
                        horizontal-alignment: center; 
                    }
                    date: 20;
                }
                frame-72 := Rectangle {
                    x: 38px;
                    y: 4px;
                    width: 94px;
                    height: 30px;
                    in-out property <string> city;
                    in-out property <string> country;
                    city_text := Text {
                        x: 0px;
                        y: 0px;
                        text: city;
                        color: #ffffff;
                        font-family: "Roboto Mono";
                        font-size: 10.5px;
                        font-weight: 500;
                        horizontal-alignment: left; 
                    }
                    city: "Tokio";
                    country_text := Text {
                        x: 0px;
                        y: 16px;
                        text: country;
                        color: #ffffffcc;
                        font-family: "Roboto Mono";
                        font-size: 9px;
                        font-weight: 400;
                        horizontal-alignment: left; 
                    }
                    country: "Japan";
                }
                frame-97 := Rectangle {
                    x: 141px;
                    y: 0px;
                    width: 75px;
                    height: 38px;
                    in property <string> temp;
                    
                    temperature_text := Text {
                        x: 30px;
                        text: temp;
                        color: #ffffff;
                        font-family: "Roboto Mono";
                        font-size: 25px;
                        font-weight: 500;
                        horizontal-alignment: left; 
                    }
                    temp: "28°";
                    weather := Image {
                        x: 0px;
                        y: 7px;
                        width: 24px;
                        height: 24px;
                        source: @image-url("assets/weather.svg");
                    }
                }
            }
        }
        frame-96 := Rectangle {
            x: 0px;
            y: 45px;
            width: 216px;
            height: 30px;
            in property <string> vibes;
            optimal-breeze-vibes-balanced := Text {

                text: "Optimal breeze. \nVibes: balanced.";
                wrap: word-wrap;
                x:0;
                y:0;
                width: 105px;
                height: 30px;
                color: #ffffffcc;
                font-family: "Roboto Mono";
                font-size: 10px;
                font-weight: 500;
                horizontal-alignment: left; 
            }
            vibes: "Optimal breeze.Vibes: balanced.";
            view-all-stats := Text {
                x: 115.5px;
                y: 18px;
                text: "View all stats";
                color: #ffffffcc;
                font-family: "Roboto Mono";
                font-size: 8px;
                font-weight: 500;
                horizontal-alignment: right; 
            }
        }
    }
    frame-107 := Rectangle {
        x: 12px;
        y: 125px;
        width: 216px;
        height: 119px;
        TouchArea {
            clicked => {
                go_to_iot();
            }
        }
        frame-64 := Rectangle {
            x: 0px;
            y: 0px;
            width: 216px;
            height: 56px;
            border-width: 1px;
            border-color: #ffffff33;
            frame-77 := Rectangle {
                x: 15px;
                y: 19px;
                width: 186px;
                height: 18px;
                frame-106 := Rectangle {
                    x: 0px;
                    y: -1.5px;
                    width: 95px;
                    height: 21px;
                    frame-73 := Rectangle {
                        x: 0px;
                        y: 0.5px;
                        width: 20px;
                        height: 20px;
                        iot := Image {
                            source: @image-url("assets/carbon_iot-connect.svg");
                        }
                    }
                    iot_text := Text {
                        x: 24px;
                        text: "IOT";
                        color: #89dd47;
                        font-family: "Roboto Mono";
                        font-size: 14px;
                        font-weight: 500;
                        horizontal-alignment: left;
                    }
                    explore_text := Text {
                        x: 145px;
                        y: 1.5px;
                        text: "Explore";
                        color: #ffffff;
                        font-family: "Roboto Mono";
                        font-size: 10px;
                        font-weight: 500;
                        horizontal-alignment: left;
                    }
                }
            }

        }
        frame-95 := Rectangle {
            x: 0px;
            y: 63px;
            width: 216px;
            height: 56px;
            TouchArea {
                clicked => {
                    root.go_to_game();
                }
            }
            frame-62 := Rectangle {
                x: 0px;
                y: 0px;
                width: 105px;
                height: 56px;
                background: #ffffff1a;
                iconset := Rectangle {
                    x: 40.5px;
                    y: 16px;
                    width: 24px;
                    height: 24px;
                    border-radius: 8px;
                    Image {
                        source: @image-url("assets/OKZOO-logo.svg");
                    }
                }
            }
            frame-63 := Rectangle {
                x: 111px;
                y: 0px;
                width: 105px;
                height: 56px;
                background: #ffffff1a;
                frame-12 := Rectangle {
                    x: 6px;
                    y: 7px;
                    width: 93px;
                    height: 42px;
                    border-radius: 63.36px;
                    TouchArea {
                        clicked => {
                            root.go_to_ai();
                        }
                    }
                    frame-74 := Rectangle {
                        x: 32.5px;
                        y: 0px;
                        width: 28px;
                        height: 28px;
                        rectangle-2 := Rectangle {
                            x: 4px;
                            y: 4px;
                            width: 20px;
                            height: 20px;
                            border-radius: 999px;
                            border-width: 4px;
                            border-color: @linear-gradient(165deg, #cde800 0%, #efdede 50%, #dee36f 100%);
                        }
                    }
                    frame-75 := Rectangle {
                        x: 12.72px;
                        y: 30px;
                        width: 67.56px;
                        height: 12px;
                        ai := Text {
                            x: 0px;
                            text: "AI";
                            color: #ffffff;
                            font-family: "Roboto Mono";
                            font-size: 8px;
                            font-weight: 500;
                            horizontal-alignment: left; 
                        }
                        coming-soon := Text {
                            x: 12.56px;
                            text: "Coming Soon";
                            color: #ffffffcc;
                            font-family: "Roboto Mono";
                            font-size: 8px;
                            font-weight: 500;
                            horizontal-alignment: left; 
                        }
                    }
                }
            }
        }
    }
    frame-111 := Rectangle {
        x: 103px;
        y: 285px;
        width: 122px;
        height: 23px;
        frame-110 := Rectangle {
            x: 0px;
            y: 0px;
            width: 57px;
            height: 23px;
            background: #ffffff1a;
            sensors := Text {
                text: "Sensors";
                color: #ffffff;
                font-family: "Roboto Mono";
                font-size: 10px;
                font-weight: 500;
                horizontal-alignment: left;
            }
            TouchArea {
                width: parent.width;
                height: parent.height;
                //visible: false;
                clicked => {
                    root.go_to_sensor();
                }
            }
        }
        frame-109 := Rectangle {
            x: 59px;
            y: 0px;
            width: 63px;
            height: 23px;
            TouchArea {
                clicked => {
                    root.go_to_setting();
                }
            }
            background: #ffffff1a;
            settings := Text {
                text: "Settings";
                color: #ffffff;
                font-family: "Roboto Mono";
                font-size: 10px;
                font-weight: 500;
                horizontal-alignment: left;
            }
        }

    }
    link-device := Rectangle {
        x: 12px;
        y: 276px;
        width: 32px;
        height: 32px;
        border-width: 0.667px;
        border-color: #ffffff33;
        phone-camera-line := Image {
            x: 8px;
            y: 8px;
            width: 16px;
            height: 16px;
            Image {
                source: @image-url("assets/phone-camera-line.svg");
                TouchArea {
                    width: 56px;
                    height: 40px;
                    clicked => {
                        device_link();
                    }
                }
            }

        }
    }
}