export component LoadingScreenText inherits Rectangle {
    
    setup-done-code-done-directing-to-game-loading := Text {
        x: 12px;
        y: 44px;
        width: 111px;
        height: 60px;
        text: "> Setup DONE\n> Code DONE \n> Directing to Game \n/// Loading...";
        color: #ffffff;
        font-family: "Roboto Mono";
        font-size: 10px;
        font-weight: 500;
        horizontal-alignment: left; 
    }   
} 