
import { ProgressIndicator} from "std-widgets.slint";

export component RoundProgress inherits Rectangle { 
    in property <color> inner_color;  
    in-out property <bool> enable: false;
    in-out property <int> progress_value: 0;
    callback game_done();

    Rectangle {
        rectangle := Rectangle {
            // The background track
            x: 0px;
            y: 0px;
            background: black;
            border-width: 1px;
            border-color: #ffffff33;
        }

        fill := Rectangle {
            // The progress fill
            x: 0px;
            y: 0px;
            background: inner_color;
            width: (rectangle.width * root.progress_value) / 100;
            height: rectangle.height;
            opacity: 20%;
        }

    }
}