export component Sensor inherits Rectangle {
    x: 0;
    y: 0;
    callback go_back;
    frame-52 := Image {
        x: 12px;
        y: 36px;
        width: 32px;
        height: 32px;
        source: @image-url("assets/arrow-left-wide-line.svg");
        colorize: white;
        TouchArea {
            clicked => {
                root.go_back();
            }
        }
    }
    esp-chip-active-loading := Text {
        x: 12px;
        y: 80px;
        text: "> ESP Chip ACTIVE\n/// Loading...";
        color: #ffffff;
        font-family: "Roboto Mono";
        font-size: 10px;
        font-weight: 500;
        horizontal-alignment: left; 
    }
}