import { ListView } from "std-widgets.slint";

export component WifiScan {
    in property<[string]> wifi_scan: [
        "WiFi1",
        "WiFi2",
        "WiFi3"
    ];
    in property<int> connected_index;
    callback go_back();
    callback go_wifi_config();

    frame-131 := Rectangle {
        x: 10px;
        y: 32px;
        width: 218px;
        height: 32px;
        frame-52 := Rectangle {
            x: 0px;
            y: 0px;
            width: 32px;
            height: 32px;
            background: #ffffff1a;
            TouchArea {
                clicked => {
                    root.go_back();
                }
            }
            arrow-left-wide-line := Image {
                x: 8px;
                y: 8px;
                width: 16px;
                height: 16px;
                source: @image-url("assets/arrow-left-wide-line.svg");
            }
        }
        settings := Text {
            x: 85.5px;
            y: 8.5px;
            text: "Wifi";
            color: #ffffff;
            font-family: "Roboto Mono";
            font-size: 10px;
            font-weight: 500;
            horizontal-alignment: left; 
        }
    }
}