import { VirtualKeyboard } from "virtual_keyboard.slint";
import { LineEdit } from "std-widgets.slint";
export component WiFiConfig {

    callback go_back_wifi_scan();
    frame-52 := Image {
        x: 10px;
        y: 32px;
        width: 32px;
        height: 32px;
        TouchArea {
            clicked => {
                root.go_back_wifi_scan();
            }
        }
        source: @image-url("assets/arrow-left-wide-line.svg");
    }
    frame-117 := Rectangle {
        x: 66px;
        y: 40px;
        width: 108px;
        height: 15px;
        wifi-fill := Image {
            x: 0px;
            y: 1.5px;
            width: 12px;
            height: 12px;
            colorize: white;
            source: @image-url("assets/wifi-fill.svg");
        }
        okzoo-wifi := Text {
            x: 16px;
            text: "OKZOO Wifi";
            color: #ffffff;
            font-family: "Roboto Mono";
            font-size: 10px;
            font-weight: 500;
            horizontal-alignment: left; 
        }
    }
    frame-121 := Rectangle {
        x: 00px;
        y: 76px;
        width: 218px;
        height: 50px;
        background: #ffffff1a;
        frame-120 := TextInput {
            x: 10px;
            width: 218px;
            height: 60px;
            color: #ffffff66;
            font-family: "Roboto Mono";
            font-size: 10px;
            font-weight: 500;
            horizontal-alignment: left;
            vertical-alignment: center;
        }
        VirtualKeyboard { 
            width: 240px;
            height: 150px;
            visible: TextInputInterface.text-input-focused;
            x: 0;
            y: 110px; 
        }
        // FocusScope {}
        // if TextInputInterface.text-input-focused: VirtualKeyboard {
        //     x: 0;
        //     y: 140px;
        // }
    }
}